version: "3.9"  # optional since v1.27.0

services:
  payment-gateway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app/src
    depends_on:
      - db
  db:
    image: mongo # use latest official postgres version
    restart: always
    environment:
      MONGODB_URI: mongodb+srv://tambarie:GpY1vj3OlvLXeeGX@cluster0.ry5ub.mongodb.net/payment-gateway?retryWrites=true&w=majority
    volumes:
      - database-data:/data/db -d mongo # persist data even if container shuts down

volumes:
  database-data: